### ISSUE TITLE
Bug In line no 7 

### ISSUE THREAD

**Issue by shweta0318** [shweta0318/Devops#1]
@bipeensinha bug is line no.7

**Comment by bipeensinha** [comment]
ok iam working on it
![a](https://user-images.githubusercontent.com/49720823/129353020-d281c091-6f10-4b48-bed3-eca0d45989aa.png)

**Comment by shweta0318** [comment]
keep me posted

**Comment by bipeensinha** [comment]
thanbk i fix
![thank](https://user-images.githubusercontent.com/49720823/129353073-f731e500-fcac-4cb3-8c01-186869840e54.jpg)
